# Generated by Django 4.1.1 on 2022-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_experience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='job_description',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
