# Generated by Django 4.1.1 on 2022-10-06 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_aboutme_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
