# Generated by Django 4.1.1 on 2022-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_experience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='level',
            field=models.IntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH')], default=0),
        ),
    ]
