# Generated by Django 4.1.1 on 2022-10-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='cv',
            field=models.FileField(null=True, upload_to='cv'),
        ),
    ]
