# Generated by Django 4.1.1 on 2022-10-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_aboutme_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='phone',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
