# Generated by Django 4.1.1 on 2022-10-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_experience_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='phone',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
